learning_rate: 0.0005
batch_size: 200
sigma: 500
experience_replay: 300
max_buffer: 400
save_path: 'main/reinvent_offline/reinvent_models/runs'
AHC: 0.0
diversity_filter:
    name: "" # select from args. IdenticalMurckoScaffold, ScaffoldSimilarity, IdenticalTopologicalScaffold, NoFilter
    minscore: 0.3
    bucket_size: 5
    minsimilarity: 0.6
population_size: 1000
offspring_size: 500
mutation_rate: 0.067  # 0.067

